imageRegistry: docker.io
imagePullSecrets: []

server:
  port: 7002
  policyRepoUrl: "https://github.com/authorizon/opal-example-policy-repo"
  policyRepoSshKey: ""
  pollingInterval: 30
  dataConfigSources:
    config:
      entries: []
  broadcastUri: null
  broadcastPgsql: true
  uvicornWorkers: 4
  replicas: 1

client:
  port: 7000
  opaPort: 8181
  replicas: 1
